server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: default # 기본 프로필

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: your_password # 실제 비밀번호를 입력하세요

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # 개발 초기에는 create, 운영에서는 validate 또는 none 사용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect # dialect 경로 수정

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace # 파라미터 값 로깅

---
spring:
  config:
    activate:
      on-profile: test # 테스트 프로필

  datasource:
    url: jdbc:h2:mem:testdb # 인메모리 DB 경로 지정
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 테스트 종료 후 테이블 삭제
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect